### ISSUE TITLE
FAQ and About Page: Update Links to Wiki

### ISSUE THREAD

**Issue by crcdng** [teia-community/teia-ui-legacy#11]
**Summary of change to the FAQ/About page:**

On page
https://teia.art/about
and 
https://teia.art/faq

, change **all links which still point to the hicetnunc2000 wiki**, e.g.:

https://github.com/hicetnunc2000/hicetnunc/wiki

to point to the teia wiki, such as:

https://github.com/teia-community/teia-ui/wiki

**Comment by crcdng** [comment]
I see the links pointing again to hicetnunc. This concerns the links on both pages:

https://teia.art/about

and

https://teia.art/faq

**Comment by melMass** [comment]
> I see the links pointing again to hicetnunc. This concerns the links on both pages:
> 
> 
> 
> https://teia.art/about
> 
> 
> 
> and
> 
> 
> 
> https://teia.art/faq
> 
> 
> 
> 

Please look at your notifications I tagged you on the deployed site to check, this is not deployed yet

**Comment by crcdng** [comment]
Proposal: let's close issues after the fixes are deployed on the repo where they are reported and live in production. 

Bug report opened -> (PR made / Fix on staging / ... ) -> PR merged / Fix on main -> Fix is live -> Bug report closed

**Comment by crcdng** [comment]
The links on https://teia.art/about and https://teia.art/faq still point to the hicetnunc2000 wiki

**Comment by melMass** [comment]
Can you please stop?
