### ISSUE TITLE
Store the mint fields in local storage

### ISSUE THREAD

**Issue by kylegrover** [teia-community/teia-ui-legacy#4]
People regularly have issues with a mint failing, and then losing the description they typed out. Two steps to fix this:
1. Set proper `name` on mint form elements. Currently they display `name=input-name-not-set`
2. Save form input in localStorage? Here's an untested snippet I've adapted from other work that could be applied once step 1 is taken.

```
var form_els = document.querySelectorAll('input, textarea');

if (localStorage.getItem('mint_'+form_els[0].name) != null) {
    for (var i = 0; i < form_els.length; i++) {
        var el = form_els[i];
        el.value = localStorage.getItem('mint_'+el.name);
    }
}
function saveForm() {
    for (var i = 0; i < form_els.length; i++) {
        var el = form_els[i];
        localStorage.setItem('mint_'+el.name, el.value);
    }
}
setInterval(saveForm, 5000);
function clearForm(){
    for (var i = 0; i < form_els.length; i++) {
        var el = form_els[i];
        localStorage.setItem('mint_'+el.name, '');
        el.value = '';
    }
}
```

**Comment by melMass** [comment]
I've also made a test here, the logic is there but UX/UI could be better
https://teia-store-mint-infos.vercel.app/
https://github.com/melMass/teia-ui/tree/feature/store-mint-infos
